### ISSUE TITLE
PHP notice: Undefined index: search_by_referrer

### ISSUE THREAD

**Issue by Mark-H** [digitalpenguin/commerce_referrals#3]
https://github.com/digitalpenguin/commerce_referrals/blob/master/core/components/commerce_referrals/src/Admin/Referral/ReferralGrid.php#L26

That should do a check `array_key_exists('search_by_referrer', $options)` to prevent notices.

**Comment by digitalpenguin** [comment]
Thank you! Change has been made. :)
